#!/usr/bin/env bash

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "ShadowTunnel - Quick Start"
echo "==========================="
echo ""
echo "This script will help you quickly set up a stealth VPN server."
echo ""

if [ "$EUID" -eq 0 ]; then
    echo "Warning: Running as root is not recommended."
    echo "Continue? (y/N)"
    read -r continue_as_root
    if [[ ! $continue_as_root =~ ^[Yy]$ ]]; then
        echo "Please run the script as a regular user."
        exit 1
    fi
fi

echo "Checking system requirements..."

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Operating system: Linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Operating system: macOS"
else
    echo "Unsupported operating system: $OSTYPE"
    echo "Only Linux and macOS are supported."
    exit 1
fi

if command -v python3 &> /dev/null; then
    python_version=$(python3 --version | cut -d' ' -f2)
    echo "Python: $python_version"
else
    echo "Python 3 not found"
    echo "Please install Python 3.8 or newer."
    exit 1
fi

if command -v pip3 &> /dev/null; then
    echo "pip3: found"
else
    echo "pip3 not found"
    echo "Please install pip3."
    exit 1
fi

echo ""
echo "All system requirements met!"
echo ""

echo "Choose installation method:"
echo ""
echo "1) Quick installation (recommended for beginners)"
echo "2) Manual installation (for experienced users)"
echo "3) Show help"
echo "4) Exit"
echo ""

read -p "Choose option (1-4): " install_choice

case $install_choice in
    1)
        echo ""
        echo "Starting quick installation..."
        run_quick_install
        ;;
    2)
        echo ""
        echo "Manual installation"
        run_manual_install
        ;;
    3)
        show_help
        ;;
    4)
        echo "Goodbye!"
        exit 0
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac

run_quick_install() {
    echo ""
    echo "Configuration setup..."
    
    echo ""
    read -p "Enter usernames separated by comma (e.g., phone,laptop,desktop): " users_input
    
    if [ -z "$users_input" ]; then
        users_input="phone,laptop,desktop"
        echo "Using default users: $users_input"
    fi
    
    echo ""
    echo "Choose VPN protocols:"
    echo "1) Xray only (recommended)"
    echo "2) Xray + V2Ray"
    echo "3) Xray + Shadowsocks"
    echo "4) All protocols"
    read -p "Choose option (1-4): " protocol_choice
    
    case $protocol_choice in
        1) xray_enabled=true; v2ray_enabled=false; shadowsocks_enabled=false ;;
        2) xray_enabled=true; v2ray_enabled=true; shadowsocks_enabled=false ;;
        3) xray_enabled=true; v2ray_enabled=false; shadowsocks_enabled=true ;;
        4) xray_enabled=true; v2ray_enabled=true; shadowsocks_enabled=true ;;
        *) xray_enabled=true; v2ray_enabled=false; shadowsocks_enabled=false ;;
    esac
    
    echo ""
    read -p "Enable web management panel? (Y/n): " webpanel_choice
    webpanel_enabled=${webpanel_choice:-Y}
    
    echo ""
    read -p "Enable monitoring system? (Y/n): " monitoring_choice
    monitoring_enabled=${monitoring_choice:-Y}
    
    echo ""
    read -p "Enable automatic backup? (Y/n): " backup_choice
    backup_enabled=${backup_choice:-Y}
    
    echo ""
    echo "Creating configuration..."
    
    users_formatted=$(echo "$users_input" | tr ',' '\n' | sed 's/^/  - /' | tr '\n' ' ')
    
    cat > config.cfg << EOF
---
# Advanced VPN Server Configuration
# Generated by quick install on $(date)

# Users
users:
$users_formatted

# VPN Protocols
vpn_protocols:
  xray_enabled: $xray_enabled
  v2ray_enabled: $v2ray_enabled
  shadowsocks_enabled: $shadowsocks_enabled

# Web Panel
web_panel:
  enabled: $webpanel_enabled
  port: 2053
  username: "admin"
  password: "admin123"

# Monitoring
monitoring:
  enabled: $monitoring_enabled
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3000
    admin_password: "grafana123"

# Backup
backup:
  enabled: $backup_enabled
  schedule: "0 3 * * *"
  retention_days: 30
  encryption_enabled: true

# Security
security:
  ssh_port: 4160
  client_isolation: true
  auto_updates: true
  reboot_time: "06:00"

# Privacy
privacy:
  log_level: -1
  enhancements_enabled: true

# DNS
dns:
  encryption_enabled: true
  adblock_enabled: true
  servers:
    ipv4:
      - 1.1.1.1
      - 1.0.0.1

# Network
network:
  ipv6_enabled: true
  mtu: 0
  keepalive: 0

# Cloud Providers
cloud_providers:
  digitalocean:
    size: "s-1vcpu-1gb"
    image: "ubuntu-22-04-x64"
  ec2:
    size: "t2.micro"
    image: "ubuntu-jammy-22.04"
  gce:
    size: "e2-micro"
    image: "ubuntu-2204-lts"
EOF
    
    echo "Configuration created: config.cfg"
    
    echo ""
    echo "Installing dependencies..."
    
    if [ -f "requirements.txt" ]; then
        pip3 install --user -r requirements.txt
        echo "Dependencies installed"
    else
        echo "requirements.txt not found"
        echo "Installing basic dependencies..."
        pip3 install --user ansible pyyaml jinja2 qrcode[pil]
        echo "Basic dependencies installed"
    fi
    
    echo ""
    echo "Starting deployment..."
    echo ""
    echo "Warning: Deployment may take several minutes."
    echo ""
    
    if [ -f "./deploy" ]; then
        chmod +x ./deploy
        ./deploy
    else
        echo "deploy script not found"
        echo "Run: ansible-playbook main.yml"
    fi
    
    echo ""
    echo "Installation completed!"
    echo ""
    echo "Next steps:"
    echo "1. Check configuration files in ./configs/ directory"
    echo "2. Use connection-urls.txt for connections"
    echo "3. Open web management panel: http://your-server:2053"
    echo "4. For management use: ./deploy menu"
    echo ""
}

run_manual_install() {
    echo ""
    echo "Manual installation"
    echo ""
    echo "For manual installation, follow these steps:"
    echo ""
    echo "1. Install dependencies:"
    echo "   pip3 install -r requirements.txt"
    echo ""
    echo "2. Edit configuration:"
    echo "   nano config.cfg"
    echo ""
    echo "3. Run deployment:"
    echo "   ./deploy"
    echo ""
    echo "4. Or use interactive menu:"
    echo "   ./deploy menu"
    echo ""
    echo "Instructions shown"
}

show_help() {
    echo ""
    echo "ShadowTunnel Help"
    echo ""
    echo "What is this?"
    echo "ShadowTunnel is an automated solution for deploying"
    echo "stealth VPN servers with advanced evasion techniques."
    echo ""
    echo "Supported protocols:"
    echo "• VLESS (recommended)"
    echo "• VMess"
    echo "• Trojan"
    echo "• Shadowsocks"
    echo "• REALITY (masquerading as real sites)"
    echo ""
    echo "Multi-hop VPN:"
    echo "• Double VPN (2-hop routing)"
    echo "• Quad VPN (4-hop routing)"
    echo "• Custom chain configurations"
    echo ""
    echo "Features:"
    echo "• Web management panel"
    echo "• Monitoring system (Prometheus + Grafana)"
    echo "• Automatic backups"
    echo "• Automatic updates"
    echo "• Docker support"
    echo "• Cloud integration"
    echo ""
    echo "Web interfaces:"
    echo "• Management: http://your-server:2053"
    echo "• Monitoring: http://your-server:3000"
    echo "• Metrics: http://your-server:9090"
    echo ""
    echo "Important files:"
    echo "• config.cfg - main configuration"
    echo "• configs/ - generated configurations"
    echo "• connection-urls.txt - connection URLs"
    echo ""
    echo "Need help?"
    echo "• GitHub Issues: https://github.com/yourusername/shadowtunnel/issues"
    echo "• Documentation: docs/USAGE.md"
    echo ""
}

echo ""
echo "Script completed"